import React from "react";
const prices = [
  {
    id: 1,
    title: "Relaxante",
    m1: "Massagem Única:",
    p1: "R$ 90",
    m2: "Pacote (4 sessões):",
    p2: "R$ 300",
    p3: "R$ 120",
    p4: "R$ 380",
  },
  {
    id: 2,
    title: "Drenagem Linfática",
    m1: "Massagem Individual:",
    p1: "R$ 90",
    m2: "Pacote (4 sessões):",
    p2: "R$ 300",
    p3: "R$ 120",
    p4: "R$ 380",
  },
  {
    id: 3,
    title: "Ayurveda",
    m1: "Massagem Única:",
    p1: "R$ 120",
    m2: "Pacote (4 sessões):",
    p2: "R$ 380",
    p3: "R$ 140",
    p4: "R$ 480",
  },
  {
    id: 4,
    title: "Lipomodelagem Vegana",
    m1: "Massagem Individual:",
    p1: "R$ 120",
    m2: "Pacote (4 sessões):",
    p2: "R$ 380",
    p3: "R$ 140",
    p4: "R$ 480",
  },
  {
    id: 5,
    title: "Reiki",
    m1: "Sessão Única:",
    p1: "R$ 70",
    m2: "Pacote (4 sessões):",
    p2: "R$ 240",
    p3: "R$ 90",
    p4: "R$ 320",
  },
  {
    id: 6,
    title: "Aromaterapia",
    m1: "Consulta",
    p1: "R$ 120",
    m2: "",
    p2: "",
    p3: "",
    p4: "",
  },
  {
    id: 7,
    title: "Auricoloterapia",
    m1: "Sessão Única:",
    p1: "R$ 70",
    m2: "Pacote (4 sessões):",
    p2: "R$ 240",
    p3: "R$ 90",
    p4: "R$ 320",
  },
  {
    id: 8,
    title: "Ventosaterapia",
    m1: "Sessão Única:",
    p1: "R$ 70",
    m2: "Pacote (4 sessões):",
    p2: "R$ 240",
    p3: "R$ 90",
    p4: "R$ 320",
  },
];

export default prices;
