import React from "react";
const prices = [
  {
    id: 1,
    title: "Relaxante**",
    m1: "Massagem Única:",
    p1: "R$ 100",
    m2: "Pacote (4 sessões):",
    p2: "R$ 320",
    p3: "R$ 120",
    p4: "R$ 400",
    includes:
      "**Inclui: 🌷 Aromaterapia - com óleos terapêuticos totalmente naturais, preparados especialmente para cada indivíduo. 🌷 Aplicação de magnetos (auxilia no equilíbrio geral e alívio de dores). 🌷 Ventosas (caso necessário) 🌷 Reiki (algumas sessões, conforme necessidade)🌷 Alinhamento de Chakras com cristais, conforme necessidade e desejo do cliente",
  },
  {
    id: 2,
    title: "Drenagem Linfática",
    m1: "Massagem Individual:",
    p1: "R$ 100",
    m2: "Pacote (4 sessões):",
    p2: "R$ 320",
    p3: "R$ 120",
    p4: "R$ 400",
    includes: "",
  },
  {
    id: 3,
    title: "Ayurveda",
    m1: "Massagem Única:",
    p1: "R$ 120",
    m2: "Pacote (4 sessões):",
    p2: "R$ 380",
    p3: "R$ 140",
    p4: "R$ 480",
    includes: "",
  },
  {
    id: 4,
    title: "Lipomodelagem Vegana**",
    m1: "Massagem Individual:",
    p1: "R$ 120",
    m2: "Pacote (4 sessões):",
    p2: "R$ 380",
    p3: "R$ 140",
    p4: "R$ 480",
    includes:
      "**Inclui: 🌷 Suco e chá Detox 🌷 Manta térmica 🌷 Argila (opcional) 🌷 Óleos específicos com ativos desintoxicantes, estimulantes do metabolismo e do sistema linfático e circulatório, etc.🌷 Massagem no corpo todo (dura em média 1h30)",
  },
  {
    id: 5,
    title: "Reiki**",
    m1: "Sessão Única:",
    p1: "R$ 70",
    m2: "Pacote (4 sessões):",
    p2: "R$ 240",
    p3: "R$ 90",
    p4: "R$ 320",
    includes:
      "**Inclui: 🌷Análise dos Chakras com o pêndulo 🌷 Aromaterapia 🌷Cristais",
  },
  {
    id: 6,
    title: "Aromaterapia**",
    m1: "Consulta",
    p1: "R$ 120",
    m2: "",
    p2: "",
    p3: "",
    p4: "",
    includes:
      "**Inclui: 🌷 A consulta inclui análise da situação, determinação da abordagem Terapêutica e aplicação com toque terapêutico e inalação. Por exemplo, massagem nas mãos e nos pés. Também está incluso a consulta de retorno. 🌷 As formulações que serão utilizadas no tratamento não estão inclusas nesse valor. Por exemplo: inalador pessoal, perfume terapêutico, óleo corporal e/ou facial e spray.",
  },
  {
    id: 7,
    title: "Auricoloterapia",
    m1: "Sessão Única:",
    p1: "R$ 70",
    m2: "Pacote (4 sessões):",
    p2: "R$ 240",
    p3: "R$ 90",
    p4: "R$ 320",
    includes: "",
  },
  {
    id: 8,
    title: "Ventosaterapia",
    m1: "Sessão Única:",
    p1: "R$ 70",
    m2: "Pacote (4 sessões):",
    p2: "R$ 240",
    p3: "R$ 90",
    p4: "R$ 320",
    includes: "",
  },{
    id: 9,
    title: "Massagens Especiais: Pedras Quentes • Velas • Pindas Chinesas",
    m1: "Sessão Única:",
    p1: "R$ 110",
    m2: "Pacote (4 sessões):",
    p2: "R$ 380",
    p3: "R$ 130",
    p4: "R$ 440",
    includes: "",
  },
];

export default prices;
